"""Refresh DuckDB sample company/declaration/risk data with realistic demo rows.

The 13 primary rows are based on the PDF extraction cache generated by
extract_import_pdf_samples.py. They are still demo data, but the company names,
addresses, customs brokers, declarations, and risk indicators are shaped to
look like coherent importer profiles instead of placeholder "(샘플)업종기업" rows.

2026 재설계: 수입신고서(관세법 시행규칙 별지 제1호의3서식) 5개 영역 전체를
정규화 4-테이블로 표현한다.
  import_declarations            (헤더 1건: 영역1 신고/당사자 · 영역2 화물·운송 · 영역3 거래·결제 · 영역5 세액합계)
    └─ import_declaration_items        (영역4 품목/란 N개 반복)
          ├─ import_declaration_item_specs   (모델·규격별 하위 반복)
          └─ import_declaration_item_taxes   (품목별 세목 반복: 관세 + 내국세)
헤더에는 기존 대표값 컬럼(hs_code·item_name·declared_value·origin_country·
origin_country_name)을 그대로 유지하여 기존 소비처(위험지표 산출·Neo4j 적재·
웹서버·NL2SQL 등)가 수정 없이 동작하게 한다. 신규 필드는 모두 추가만 된다.
"""

from __future__ import annotations

import json
import shutil
import sys
from datetime import datetime, timedelta
from pathlib import Path

import duckdb


ROOT = Path(__file__).resolve().parents[2]
DB_PATH = ROOT / "data" / "customs.duckdb"
EXTRACT_PATH = ROOT / "data" / "sample_import_pdf_extracts.json"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from src.countries import country_code, country_name  # noqa: E402


COMPANY_META = [
    {
        "company_id": "C-2001",
        "company_name": "홈리빙코리아 주식회사",
        "industry_code": "G46",
        "founded_year": 2012,
        "address_postal_code": "04526",
        "address": "서울특별시 중구 세종대로 136",
        "address_detail": "파이낸스센터 18층",
        "employee_count": 84,
        "major_export_countries": "인도네시아, 베트남, 중국",
        "customs_broker_firm": "세종합동관세사무소",
        "related_companies": "Home Living Asia Pte. Ltd.",
        "annual_multiplier": 9.5,
        "duty_rate": 0.076,
        "refund_rate": 0.012,
        "fta_reduction_rate": 10.0,
        "risk_level": "MEDIUM",
        "risk_score": 61.8,
        "risk": (48.0, 18.0, 24.0, 12.0, 35.0, 16.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2002",
        "company_name": "코리아디지털트레이딩 주식회사",
        "industry_code": "G46",
        "founded_year": 2018,
        "address_postal_code": "06158",
        "address": "서울특별시 강남구 테헤란로 419",
        "address_detail": "강남파이낸스플라자 9층",
        "employee_count": 42,
        "major_export_countries": "중국, 홍콩, 대만",
        "customs_broker_firm": "한빛관세법인",
        "related_companies": "Korea Trading HK Ltd.",
        "annual_multiplier": 14.0,
        "duty_rate": 0.061,
        "refund_rate": 0.018,
        "fta_reduction_rate": 6.5,
        "risk_level": "HIGH",
        "risk_score": 76.4,
        "risk": (72.0, 38.0, 19.0, 22.0, 54.0, 36.0),
        "status": "INSPECT",
    },
    {
        "company_id": "C-2003",
        "company_name": "세미콘솔루션코리아 유한회사",
        "industry_code": "C28",
        "founded_year": 2009,
        "address_postal_code": "18469",
        "address": "경기도 화성시 동탄첨단산업1로 27",
        "address_detail": "동탄테크노밸리 A동 1104호",
        "employee_count": 118,
        "major_export_countries": "일본, 미국, 싱가포르",
        "customs_broker_firm": "동탄관세법인",
        "related_companies": "Semicon Solution Japan KK",
        "annual_multiplier": 8.0,
        "duty_rate": 0.044,
        "refund_rate": 0.006,
        "fta_reduction_rate": 4.2,
        "risk_level": "MEDIUM",
        "risk_score": 69.7,
        "risk": (42.0, 34.0, 11.0, 8.0, 63.0, 28.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2004",
        "company_name": "프레시푸드코리아 주식회사",
        "industry_code": "G46",
        "founded_year": 2015,
        "address_postal_code": "22379",
        "address": "인천광역시 중구 축항대로 64",
        "address_detail": "냉동물류센터 3층",
        "employee_count": 73,
        "major_export_countries": "태국, 페루, 칠레",
        "customs_broker_firm": "인천항관세사법인",
        "related_companies": "Fresh Food Thailand Co., Ltd.",
        "annual_multiplier": 6.5,
        "duty_rate": 0.094,
        "refund_rate": 0.031,
        "fta_reduction_rate": 38.5,
        "risk_level": "HIGH",
        "risk_score": 82.1,
        "risk": (58.0, 42.0, 71.0, 64.0, 33.0, 27.0),
        "status": "HOLD",
    },
    {
        "company_id": "C-2005",
        "company_name": "펫라이프코리아 주식회사",
        "industry_code": "G47",
        "founded_year": 2020,
        "address_postal_code": "10403",
        "address": "경기도 고양시 일산동구 중앙로 1036",
        "address_detail": "웨스턴타워 1208호",
        "employee_count": 31,
        "major_export_countries": "튀르키예, 중국, 캐나다",
        "customs_broker_firm": "고양관세사무소",
        "related_companies": "Pet Life Global Trading",
        "annual_multiplier": 18.0,
        "duty_rate": 0.052,
        "refund_rate": 0.011,
        "fta_reduction_rate": 13.0,
        "risk_level": "MEDIUM",
        "risk_score": 55.9,
        "risk": (31.0, 22.0, 20.0, 16.0, 29.0, 18.0),
        "status": "NORMAL",
    },
    {
        "company_id": "C-2006",
        "company_name": "메디케어코리아 유한회사",
        "industry_code": "C27",
        "founded_year": 2016,
        "address_postal_code": "08390",
        "address": "서울특별시 구로구 디지털로 288",
        "address_detail": "대륭포스트타워 2차 705호",
        "employee_count": 56,
        "major_export_countries": "대만, 일본, 독일",
        "customs_broker_firm": "구로디지털관세법인",
        "related_companies": "Medicare Taiwan Ltd.",
        "annual_multiplier": 22.0,
        "duty_rate": 0.048,
        "refund_rate": 0.007,
        "fta_reduction_rate": 9.0,
        "risk_level": "MEDIUM",
        "risk_score": 64.2,
        "risk": (28.0, 21.0, 16.0, 9.0, 58.0, 19.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2007",
        "company_name": "스타일플러스코리아 주식회사",
        "industry_code": "C13",
        "founded_year": 2011,
        "address_postal_code": "04782",
        "address": "서울특별시 성동구 아차산로 17",
        "address_detail": "서울숲IT밸리 1002호",
        "employee_count": 97,
        "major_export_countries": "베트남, 방글라데시, 캄보디아",
        "customs_broker_firm": "성동관세법인",
        "related_companies": "Style Plus Vietnam Co., Ltd.",
        "annual_multiplier": 7.2,
        "duty_rate": 0.13,
        "refund_rate": 0.025,
        "fta_reduction_rate": 47.0,
        "risk_level": "HIGH",
        "risk_score": 74.6,
        "risk": (63.0, 29.0, 68.0, 34.0, 51.0, 22.0),
        "status": "INSPECT",
    },
    {
        "company_id": "C-2008",
        "company_name": "헬스세이프코리아 주식회사",
        "industry_code": "C21",
        "founded_year": 2019,
        "address_postal_code": "34141",
        "address": "대전광역시 유성구 대학로 291",
        "address_detail": "바이오벤처센터 406호",
        "employee_count": 45,
        "major_export_countries": "말레이시아, 중국, 싱가포르",
        "customs_broker_firm": "충청관세법인",
        "related_companies": "Health Safe Malaysia Sdn. Bhd.",
        "annual_multiplier": 8.0,
        "duty_rate": 0.08,
        "refund_rate": 0.018,
        "fta_reduction_rate": 21.0,
        "risk_level": "MEDIUM",
        "risk_score": 67.5,
        "risk": (41.0, 24.0, 33.0, 22.0, 49.0, 21.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2009",
        "company_name": "오토파트코리아 주식회사",
        "industry_code": "C30",
        "founded_year": 2008,
        "address_postal_code": "16648",
        "address": "경기도 수원시 권선구 산업로 156",
        "address_detail": "수원산업단지 2동",
        "employee_count": 132,
        "major_export_countries": "독일, 멕시코, 중국",
        "customs_broker_firm": "경기관세법인",
        "related_companies": "Auto Parts Europe GmbH",
        "annual_multiplier": 6.8,
        "duty_rate": 0.055,
        "refund_rate": 0.013,
        "fta_reduction_rate": 18.0,
        "risk_level": "HIGH",
        "risk_score": 72.8,
        "risk": (46.0, 44.0, 18.0, 15.0, 66.0, 31.0),
        "status": "INSPECT",
    },
    {
        "company_id": "C-2010",
        "company_name": "키즈월드코리아 주식회사",
        "industry_code": "G47",
        "founded_year": 2017,
        "address_postal_code": "08510",
        "address": "서울특별시 금천구 벚꽃로 278",
        "address_detail": "SJ테크노빌 1510호",
        "employee_count": 66,
        "major_export_countries": "중국, 홍콩, 베트남",
        "customs_broker_firm": "금천합동관세사무소",
        "related_companies": "Kids World Shenzhen Trading",
        "annual_multiplier": 8.8,
        "duty_rate": 0.08,
        "refund_rate": 0.019,
        "fta_reduction_rate": 12.0,
        "risk_level": "HIGH",
        "risk_score": 73.5,
        "risk": (57.0, 35.0, 24.0, 18.0, 61.0, 26.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2011",
        "company_name": "브라이트테크코리아 주식회사",
        "industry_code": "C26",
        "founded_year": 2021,
        "address_postal_code": "14055",
        "address": "경기도 안양시 동안구 시민대로 327",
        "address_detail": "스마트스퀘어 614호",
        "employee_count": 28,
        "major_export_countries": "중국, 대만",
        "customs_broker_firm": "안양관세사무소",
        "related_companies": "Bright Tech Shenzhen Co., Ltd.",
        "annual_multiplier": 24.0,
        "duty_rate": 0.04,
        "refund_rate": 0.009,
        "fta_reduction_rate": 5.0,
        "risk_level": "MEDIUM",
        "risk_score": 66.9,
        "risk": (54.0, 39.0, 15.0, 11.0, 47.0, 33.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2012",
        "company_name": "키친메이트코리아 주식회사",
        "industry_code": "G46",
        "founded_year": 2014,
        "address_postal_code": "07238",
        "address": "서울특별시 영등포구 은행로 11",
        "address_detail": "일신빌딩 703호",
        "employee_count": 52,
        "major_export_countries": "중국, 베트남, 인도네시아",
        "customs_broker_firm": "여의도관세법인",
        "related_companies": "Kitchen Mate Ningbo Co., Ltd.",
        "annual_multiplier": 17.0,
        "duty_rate": 0.082,
        "refund_rate": 0.015,
        "fta_reduction_rate": 17.5,
        "risk_level": "MEDIUM",
        "risk_score": 59.8,
        "risk": (38.0, 27.0, 25.0, 17.0, 37.0, 20.0),
        "status": "NORMAL",
    },
    {
        "company_id": "C-2013",
        "company_name": "뷰티코리아 주식회사",
        "industry_code": "G46",
        "founded_year": 2010,
        "address_postal_code": "06019",
        "address": "서울특별시 강남구 도산대로 317",
        "address_detail": "호림아트센터 8층",
        "employee_count": 91,
        "major_export_countries": "프랑스, 이탈리아, 미국",
        "customs_broker_firm": "강남관세법인",
        "related_companies": "Beauty Korea Paris SARL",
        "annual_multiplier": 7.0,
        "duty_rate": 0.064,
        "refund_rate": 0.014,
        "fta_reduction_rate": 29.0,
        "risk_level": "HIGH",
        "risk_score": 75.2,
        "risk": (62.0, 41.0, 47.0, 21.0, 45.0, 35.0),
        "status": "INSPECT",
    },
]


# 2-letter ISO/영문 표기 → alpha-3 코드 보정 (한글명은 src.countries가 처리)
ORIGIN_FIX = {
    "THAILAND": "THA",
    "CN": "CHN",
    "JP": "JPN",
    "TW": "TWN",
    "TR": "TUR",
    "VN": "VNM",
    "MY": "MYS",
    "DE": "DEU",
    "FR": "FRA",
}


SYNTHETIC_NAMES = {
    "C20": ["동진케미칼", "한서소재", "대양폴리머", "케이피화학무역"],
    "G46": ["서진글로벌트레이드", "태원인터내셔널", "유니온소싱", "에이스커머스"],
    "C13": ["한빛어패럴", "신성텍스타일", "동남섬유", "오름패브릭"],
    "C26": ["넥스전자부품", "루멘테크", "에스엠디솔루션", "코어일렉트로닉스"],
    "C30": ["진성모빌리티", "태광오토텍", "케이모터스부품", "우진브레이크"],
    "C21": ["바이오세이프", "메디젠랩", "휴먼헬스케어", "케이파마소싱"],
    "G47": ["리빙앤리테일", "제이펫커머스", "키즈앤홈", "제주라이프몰"],
}


# ── 수입신고서 4-테이블 컬럼 정의 (setup_db.py가 그대로 재사용) ─────────────────

HEADER_COLS = [
    # 기존 대표값/식별 (영역4 첫 란 + 신고 식별) — 기존 소비처 호환 유지
    "id", "company_id", "declaration_no", "hs_code", "item_name", "declared_value",
    "origin_country", "origin_country_name", "import_date", "status",
    # 영역1: 기본 신고 및 당사자 정보
    "customs_office_code", "declaration_type", "clearance_plan",
    "filer_name", "filer_representative",
    "importer_name", "importer_person_name", "importer_customs_code", "importer_is_taxpayer",
    "taxpayer_address", "taxpayer_name", "taxpayer_person_name", "taxpayer_phone",
    "taxpayer_email", "taxpayer_customs_code", "taxpayer_business_no",
    "overseas_supplier_name", "overseas_supplier_country", "overseas_supplier_code",
    # 영역2: 화물 및 운송 정보
    "electronic_invoice_no", "bl_awb_no", "cargo_control_no", "master_bl_awb_no",
    "forwarder_name", "forwarder_code",
    "departure_country", "arrival_port", "transport_type", "vessel_name",
    "vessel_nationality", "carrier_code",
    "arrival_date", "warehousing_date", "inspection_location",
    "total_weight", "total_weight_unit", "total_packages", "package_type",
    # 영역3: 거래 및 결제 / 총 과세 정보
    "transaction_type", "import_type", "collection_type",
    "origin_cert_flag", "price_declaration_flag",
    "payment_incoterms", "payment_currency", "payment_amount", "payment_method",
    "exchange_rate", "freight_krw", "insurance_krw", "addition_krw", "deduction_krw",
    "total_customs_value_usd", "total_customs_value_krw",
    # 영역5: 세액 합계 및 정산 정보
    "tax_customs_duty", "tax_individual_consumption", "tax_traffic", "tax_liquor",
    "tax_education", "tax_rural_special", "tax_vat",
    "penalty_late_declaration", "penalty_non_declaration",
    "total_tax_amount", "total_vat_base", "total_vat_exempt_base",
]

ITEM_COLS = [
    "item_id", "declaration_id", "line_no",
    "tariff_item_name_en", "trade_item_name_en", "hsk_code", "simple_tariff_code",
    "brand_code", "brand_name",
    "net_weight", "net_weight_unit", "tariff_quantity", "tariff_quantity_unit",
    "refund_quantity", "refund_quantity_unit",
    "origin_country", "origin_criteria", "origin_marking",
    "import_requirement_type", "import_requirement_approval_no", "import_requirement_doc",
    "import_requirement_issue_date", "import_requirement_law_code", "post_verification_agency",
    "item_customs_value_usd", "item_customs_value_krw", "special_tax_basis",
]

SPEC_COLS = [
    "spec_id", "item_id", "seq",
    "model_spec", "ingredient", "spec_quantity", "spec_quantity_unit",
    "spec_unit_price", "spec_amount", "currency",
]

TAX_COLS = [
    "tax_id", "item_id", "seq",
    "tax_type", "rate_type", "tax_rate", "reduction_rate", "tax_amount",
    "reduction_installment_code", "reduction_amount", "internal_tax_code",
]


# ── 신고서 영역2~4 현실값 디테일 (회사별) ─────────────────────────────────────
# 파생 가능한 값(세액·운임·USD환산·번호류)은 빌더가 계산하고, 회사별로 의미 있게
# 달라지는 값(통화/인도조건/운송수단/요건/품목 구성)만 여기서 지정한다.

EXCHANGE_RATES = {"USD": 1350.0, "JPY": 9.1, "EUR": 1465.0, "CNY": 188.0, "THB": 38.0}

_REQ = {
    "food": ("21 수입식품", "수입식품등의 수입신고확인증", "식품위생법", "식품의약품안전처"),
    "quasidrug": ("22 의약외품", "의약외품 수입요건확인서", "약사법", "식품의약품안전처"),
    "cosmetic": ("23 화장품", "화장품 수입요건확인서", "화장품법", "식품의약품안전처"),
    "device": ("24 의료기기", "의료기기 수입요건확인서", "의료기기법", "식품의약품안전처"),
}

# 회사별 디테일. items[*]: line_no, 영문 품명, HSK10, 상표, 품목 과세가격(원화),
# 순중량(kg), 수량/단위, 관세율(소수), 요건키(None), 모델·규격 specs
DECL_DETAIL = {
    "C-2001": {  # 목재 가구 (다품목)
        "currency": "USD", "incoterms": "FOB", "transport": "SEA", "origin_cert": "Y",
        "package_type": "PALLET",
        "items": [
            {"line_no": 1, "tariff_en": "WOODEN DINING CHAIR", "trade_en": "DINING WOODEN CHAIR",
             "hsk": "9401610000", "brand": "HOMELIVING", "value_krw": 56_160_000, "net_kg": 8400,
             "qty": 1200, "qty_unit": "EA", "duty_rate": 0.0, "req": None,
             "specs": [("OAK-DC100 / 등받이 원목", "RUBBER WOOD 100%", 1200, "EA")]},
            {"line_no": 2, "tariff_en": "WOODEN DINING TABLE", "trade_en": "DINING WOODEN TABLE",
             "hsk": "9403609000", "brand": "HOMELIVING", "value_krw": 30_000_000, "net_kg": 6000,
             "qty": 300, "qty_unit": "EA", "duty_rate": 0.08, "req": None,
             "specs": [("OAK-DT200 / 4인용 1500x800", "RUBBER WOOD 100%", 300, "EA")]},
        ],
    },
    "C-2002": {  # 노트북 + 어댑터 (다품목)
        "currency": "USD", "incoterms": "CIF", "transport": "SEA", "origin_cert": "Y",
        "package_type": "CARTON",
        "items": [
            {"line_no": 1, "tariff_en": "PORTABLE AUTOMATIC DATA PROCESSING MACHINE",
             "trade_en": "NOTEBOOK COMPUTER", "hsk": "8471300000", "brand": "KDT",
             "value_krw": 50_000_000, "net_kg": 750, "qty": 500, "qty_unit": "EA",
             "duty_rate": 0.0, "req": None,
             "specs": [("KDT-NB15 / 15.6인치 i5 16GB", "ALUMINUM ALLOY BODY", 500, "EA")]},
            {"line_no": 2, "tariff_en": "POWER ADAPTER 65W", "trade_en": "AC POWER ADAPTER",
             "hsk": "8504408000", "brand": "KDT", "value_krw": 8_000_000, "net_kg": 200,
             "qty": 500, "qty_unit": "EA", "duty_rate": 0.08, "req": None,
             "specs": [("KDT-AD65 / 65W USB-C", "PC + COPPER", 500, "EA")]},
        ],
    },
    "C-2003": {  # 반도체 진공펌프
        "currency": "JPY", "incoterms": "CIF", "transport": "SEA", "origin_cert": "N",
        "package_type": "WOODEN CASE",
        "items": [
            {"line_no": 1, "tariff_en": "VACUUM PUMPS", "trade_en": "DRY VACUUM PUMP",
             "hsk": "8414100000", "brand": "SEMICON", "value_krw": 201_190_000, "net_kg": 5200,
             "qty": 40, "qty_unit": "EA", "duty_rate": 0.08, "req": None,
             "specs": [("VP-DRY3000 / 배기속도 3000L/min", "STEEL + ALUMINUM", 40, "EA")]},
        ],
    },
    "C-2004": {  # 냉동 과일 (다품목, 식품요건)
        "currency": "USD", "incoterms": "CFR", "transport": "SEA", "origin_cert": "Y",
        "package_type": "REEFER CARTON",
        "items": [
            {"line_no": 1, "tariff_en": "MANGOES, FROZEN", "trade_en": "FROZEN MANGO CHUNK",
             "hsk": "0811905090", "brand": "FRESHFOOD", "value_krw": 320_000_000, "net_kg": 96000,
             "qty": 96000, "qty_unit": "KG", "duty_rate": 0.30, "req": "food",
             "specs": [("FM-CHUNK / 무가당 냉동", "MANGO 100%", 96000, "KG")]},
            {"line_no": 2, "tariff_en": "PINEAPPLES, FROZEN", "trade_en": "FROZEN PINEAPPLE",
             "hsk": "0811909000", "brand": "FRESHFOOD", "value_krw": 154_548_000, "net_kg": 52000,
             "qty": 52000, "qty_unit": "KG", "duty_rate": 0.30, "req": "food",
             "specs": [("FP-DICE / 무가당 냉동", "PINEAPPLE 100%", 52000, "KG")]},
        ],
    },
    "C-2005": {  # 고양이 모래 (벤토나이트)
        "currency": "USD", "incoterms": "FOB", "transport": "SEA", "origin_cert": "Y",
        "package_type": "PALLET",
        "items": [
            {"line_no": 1, "tariff_en": "BENTONITE", "trade_en": "CAT LITTER BENTONITE",
             "hsk": "2508100000", "brand": "PETLIFE", "value_krw": 13_820_000, "net_kg": 42000,
             "qty": 42000, "qty_unit": "KG", "duty_rate": 0.03, "req": None,
             "specs": [("PL-CL10 / 응고형 10kg", "BENTONITE 98%", 4200, "BAG")]},
        ],
    },
    "C-2006": {  # 전자체온계 (의료기기 요건, 항공)
        "currency": "USD", "incoterms": "CIF", "transport": "AIR", "origin_cert": "N",
        "package_type": "CARTON",
        "items": [
            {"line_no": 1, "tariff_en": "DIGITAL THERMOMETER", "trade_en": "DIGITAL THERMOMETER",
             "hsk": "9025190000", "brand": "MEDICARE", "value_krw": 8_236_000, "net_kg": 180,
             "qty": 6000, "qty_unit": "EA", "duty_rate": 0.0, "req": "device",
             "specs": [("MC-DT10 / 비접촉 적외선", "ABS + SENSOR", 6000, "EA")]},
        ],
    },
    "C-2007": {  # 면 티셔츠
        "currency": "USD", "incoterms": "FOB", "transport": "SEA", "origin_cert": "Y",
        "package_type": "CARTON",
        "items": [
            {"line_no": 1, "tariff_en": "MEN'S T-SHIRTS OF COTTON, KNITTED",
             "trade_en": "MEN'S COTTON T-SHIRT", "hsk": "6109100000", "brand": "STYLEPLUS",
             "value_krw": 162_170_000, "net_kg": 9800, "qty": 70000, "qty_unit": "EA",
             "duty_rate": 0.13, "req": None,
             "specs": [("SP-TS200 / 반팔 라운드넥", "COTTON 100%", 70000, "EA")]},
        ],
    },
    "C-2008": {  # 보건용 마스크 (의약외품 요건)
        "currency": "USD", "incoterms": "CIF", "transport": "SEA", "origin_cert": "Y",
        "package_type": "CARTON",
        "items": [
            {"line_no": 1, "tariff_en": "PROTECTIVE MASK OF TEXTILE",
             "trade_en": "KF94 EQUIVALENT PROTECTIVE MASK", "hsk": "6307909000", "brand": "HEALTHSAFE",
             "value_krw": 77_870_000, "net_kg": 5400, "qty": 1_800_000, "qty_unit": "EA",
             "duty_rate": 0.10, "req": "quasidrug",
             "specs": [("HS-KF94 / 4겹 입체형", "PP NON-WOVEN + MB FILTER", 1_800_000, "EA")]},
        ],
    },
    "C-2009": {  # 브레이크 패드
        "currency": "EUR", "incoterms": "CIF", "transport": "SEA", "origin_cert": "Y",
        "package_type": "PALLET",
        "items": [
            {"line_no": 1, "tariff_en": "BRAKE LININGS AND PADS", "trade_en": "DISC BRAKE PAD SET",
             "hsk": "6813819000", "brand": "AUTOPART", "value_krw": 254_100_000, "net_kg": 28000,
             "qty": 40000, "qty_unit": "SET", "duty_rate": 0.08, "req": None,
             "specs": [("AP-BP500 / 세라믹 전륜용", "CERAMIC FRICTION MATERIAL", 40000, "SET")]},
        ],
    },
    "C-2010": {  # 블록 완구
        "currency": "USD", "incoterms": "FOB", "transport": "SEA", "origin_cert": "Y",
        "package_type": "CARTON",
        "items": [
            {"line_no": 1, "tariff_en": "TOY BUILDING BLOCKS OF PLASTICS",
             "trade_en": "PLASTIC BUILDING BLOCK TOY SET", "hsk": "9503003900", "brand": "KIDSWORLD",
             "value_krw": 116_875_000, "net_kg": 14000, "qty": 35000, "qty_unit": "SET",
             "duty_rate": 0.0, "req": None,
             "specs": [("KW-BLK320 / 320피스 세트", "ABS PLASTIC", 35000, "SET")]},
        ],
    },
    "C-2011": {  # LED 모듈 (항공)
        "currency": "USD", "incoterms": "CIF", "transport": "AIR", "origin_cert": "Y",
        "package_type": "CARTON",
        "items": [
            {"line_no": 1, "tariff_en": "LIGHT-EMITTING DIODES (LED) MODULE",
             "trade_en": "LED MODULE FOR SIGNAGE", "hsk": "8541410000", "brand": "BRIGHTTECH",
             "value_krw": 4_685_000, "net_kg": 120, "qty": 20000, "qty_unit": "EA",
             "duty_rate": 0.0, "req": None,
             "specs": [("BT-LM50 / SMD 5050 백색", "GAN LED CHIP", 20000, "EA")]},
        ],
    },
    "C-2012": {  # 스테인리스 주방용품
        "currency": "USD", "incoterms": "FOB", "transport": "SEA", "origin_cert": "Y",
        "package_type": "CARTON",
        "items": [
            {"line_no": 1, "tariff_en": "KITCHEN ARTICLES OF STAINLESS STEEL",
             "trade_en": "STAINLESS STEEL COOKWARE", "hsk": "7323930000", "brand": "KITCHENMATE",
             "value_krw": 9_400_000, "net_kg": 4200, "qty": 7000, "qty_unit": "EA",
             "duty_rate": 0.08, "req": None,
             "specs": [("KM-POT24 / 양수냄비 24cm", "STAINLESS STEEL 304", 7000, "EA")]},
        ],
    },
    "C-2013": {  # 기초화장품 (화장품 요건, 항공)
        "currency": "EUR", "incoterms": "CIF", "transport": "AIR", "origin_cert": "Y",
        "package_type": "CARTON",
        "items": [
            {"line_no": 1, "tariff_en": "BEAUTY OR MAKE-UP PREPARATIONS",
             "trade_en": "MOISTURIZING FACE CREAM", "hsk": "3304990000", "brand": "BEAUTYKOREA",
             "value_krw": 151_980_000, "net_kg": 3600, "qty": 60000, "qty_unit": "EA",
             "duty_rate": 0.065, "req": "cosmetic",
             "specs": [("BK-FC50 / 50ml 보습크림", "WATER, GLYCERIN, SHEA BUTTER", 60000, "EA")]},
        ],
    },
}


def _clean_hs(value: str | None) -> str:
    return (value or "").replace(".", "").replace("-", "")[:10]


def _origin(value: str | None) -> str:
    """원산지 표기(2-letter/영문/한글명) → ISO alpha-3 코드로 정규화."""
    text = (value or "").strip()
    if not text:
        return "UNK"
    upper = text.upper()
    for key, code in ORIGIN_FIX.items():   # 2-letter/영문 표기 보정
        if key in upper:
            return code
    return country_code(text)              # 한글명/별칭/alpha-3 처리


def _origin_name(code: str | None) -> str:
    """alpha-3 코드 → 한글 국가명."""
    return country_name(code)


def _tax_no(index: int) -> str:
    return f"{100 + index:03d}-88-{42000 + index * 137:05d}"


# ── 신고서 헤더/품목/규격/세목 행 빌더 ────────────────────────────────────────

_REPRESENTATIVES = [
    "김도현", "이수민", "박지훈", "최예린", "정민재", "한소율", "오태경",
    "서윤아", "장현우", "문가은", "임주원", "배성호", "신다영",
]
_FORWARDERS = [
    ("범한판토스(주)", "FWD2010"), ("씨제이대한통운(주)", "FWD2020"),
    ("(주)한진", "FWD2030"), ("롯데글로벌로지스(주)", "FWD2040"),
    ("DHL글로벌포워딩코리아(주)", "FWD2050"),
]
_VESSELS = [
    ("HMM ALGECIRAS", "KR"), ("ONE COLUMBA", "JP"), ("MSC ISABELLA", "PA"),
    ("COSCO SHIPPING ARIES", "CN"), ("EVER GIVEN", "PA"),
]
_FLIGHTS = [("KE", "KR"), ("OZ", "KR"), ("CX", "HK")]


def _shift_date(date_str: str | None, days: int) -> str | None:
    if not date_str:
        return None
    try:
        base = datetime.strptime(date_str, "%Y-%m-%d")
    except (TypeError, ValueError):
        return date_str
    return (base + timedelta(days=days)).strftime("%Y-%m-%d")


def _email(idx: int, company_id: str) -> str:
    return f"trade{idx:02d}@{company_id.lower().replace('-', '')}.co.kr"


def _phone(idx: int) -> str:
    return f"02-{3100 + idx:04d}-{1000 + idx * 7:04d}"


def _customs_code(company_id: str, idx: int) -> str:
    return f"{company_id.replace('-', '')}{idx:02d}M"


def build_declaration_rows(
    company_meta: list[dict], extracts: list[dict], decl_id_start: int = 2001
) -> tuple[list[dict], list[dict], list[dict], list[dict]]:
    """COMPANY_META + 추출캐시 + DECL_DETAIL을 4-테이블 행(dict)으로 변환한다.

    반환: (header_rows, item_rows, spec_rows, tax_rows)
    """
    headers: list[dict] = []
    items: list[dict] = []
    specs: list[dict] = []
    taxes: list[dict] = []

    for idx, (meta, ext) in enumerate(zip(company_meta, extracts), 1):
        decl_id = decl_id_start + idx - 1
        detail = DECL_DETAIL[meta["company_id"]]
        currency = detail["currency"]
        rate = EXCHANGE_RATES.get(currency, 1350.0)
        is_air = detail["transport"] == "AIR"

        origin_code = _origin(ext.get("origin_country"))
        origin_nm = _origin_name(origin_code)
        declared_value = int(ext.get("declared_value_krw") or 0)
        decl_item_total = sum(int(it["value_krw"]) for it in detail["items"])
        # 추출 과세가격과 품목 합계가 어긋나면 추출값을 신뢰(대표 declared_value)하되
        # 헤더 총과세가격은 품목 합계로 일관성 유지.
        total_krw = decl_item_total or declared_value

        # ── 품목/규격/세목 (영역4) ────────────────────────────────────────
        sum_duty = 0
        sum_vat = 0
        sum_net = 0.0
        sum_pkg = 0
        for it in detail["items"]:
            item_id = decl_id * 100 + it["line_no"]
            value_krw = int(it["value_krw"])
            value_usd = round(value_krw / 1350.0)
            duty = round(value_krw * it["duty_rate"])
            vat = round((value_krw + duty) * 0.10)
            sum_duty += duty
            sum_vat += vat
            sum_net += float(it["net_kg"])
            sum_pkg += int(it["qty"])

            req = _REQ.get(it["req"]) if it.get("req") else None
            items.append({
                "item_id": item_id,
                "declaration_id": decl_id,
                "line_no": it["line_no"],
                "tariff_item_name_en": it["tariff_en"],
                "trade_item_name_en": it["trade_en"],
                "hsk_code": it["hsk"],
                "simple_tariff_code": None,
                "brand_code": f"BR{item_id}",
                "brand_name": it["brand"],
                "net_weight": float(it["net_kg"]),
                "net_weight_unit": "KG",
                "tariff_quantity": float(it["qty"]),
                "tariff_quantity_unit": it["qty_unit"],
                "refund_quantity": float(it["qty"]),
                "refund_quantity_unit": it["qty_unit"],
                "origin_country": origin_code,
                "origin_criteria": "C 완전생산기준" if detail["origin_cert"] == "Y" else "X 해당없음",
                "origin_marking": "Y 적정표시" if detail["origin_cert"] == "Y" else "N 표시면제",
                "import_requirement_type": req[0] if req else None,
                "import_requirement_approval_no": f"REQ-2026-{item_id}" if req else None,
                "import_requirement_doc": req[1] if req else None,
                "import_requirement_issue_date": _shift_date(ext.get("import_date"), -5) if req else None,
                "import_requirement_law_code": req[2] if req else None,
                "post_verification_agency": req[3] if req else None,
                "item_customs_value_usd": value_usd,
                "item_customs_value_krw": value_krw,
                "special_tax_basis": None,
            })

            # 규격(모델) 하위 반복
            for s_seq, (model, ingredient, s_qty, s_unit) in enumerate(it["specs"], 1):
                unit_price_fc = round(value_krw / rate / max(1, s_qty), 2)
                specs.append({
                    "spec_id": item_id * 10 + s_seq,
                    "item_id": item_id,
                    "seq": s_seq,
                    "model_spec": model,
                    "ingredient": ingredient,
                    "spec_quantity": float(s_qty),
                    "spec_quantity_unit": s_unit,
                    "spec_unit_price": unit_price_fc,
                    "spec_amount": round(unit_price_fc * s_qty, 2),
                    "currency": currency,
                })

            # 세목 반복: 관세 + 부가가치세
            fta = detail["origin_cert"] == "Y" and it["duty_rate"] == 0.0
            taxes.append({
                "tax_id": item_id * 10 + 1,
                "item_id": item_id,
                "seq": 1,
                "tax_type": "관세",
                "rate_type": "FCN1 협정세율" if fta else "A 기본세율",
                "tax_rate": round(it["duty_rate"] * 100, 2),
                "reduction_rate": 0.0,
                "tax_amount": duty,
                "reduction_installment_code": None,
                "reduction_amount": 0,
                "internal_tax_code": None,
            })
            taxes.append({
                "tax_id": item_id * 10 + 2,
                "item_id": item_id,
                "seq": 2,
                "tax_type": "부가가치세",
                "rate_type": "A 기본세율",
                "tax_rate": 10.0,
                "reduction_rate": 0.0,
                "tax_amount": vat,
                "reduction_installment_code": None,
                "reduction_amount": 0,
                "internal_tax_code": "VA",
            })

        # ── 헤더 (영역1·2·3·5) ────────────────────────────────────────────
        first_item = detail["items"][0]
        if is_air:
            forwarder = _FORWARDERS[4]
            flight = _FLIGHTS[idx % len(_FLIGHTS)]
            vessel_name = f"{flight[0]}{870 + idx}"
            vessel_nat = flight[1]
            arrival_port = "인천공항(KRINC)"
            transport_type = "40 항공"
            customs_office = "040-72 인천공항세관 통관지원과"
            bl_awb = f"180-{20000000 + idx * 137:08d}"
            master_bl = f"{flight[0]}-{30000000 + idx * 211:08d}"
            inspection = f"인천공항 항공화물 보세창고(04072{idx:03d})"
        else:
            forwarder = _FORWARDERS[idx % len(_FORWARDERS)]
            vessel = _VESSELS[idx % len(_VESSELS)]
            vessel_name = vessel[0]
            vessel_nat = vessel[1]
            arrival_port = "부산항(KRPUS)"
            transport_type = "10 해상 FCL"
            customs_office = "030-11 부산세관 통관총괄과"
            bl_awb = f"{forwarder[1][:4]}{40000000 + idx * 173:08d}"
            master_bl = f"M{50000000 + idx * 251:09d}"
            inspection = f"부산 신항 보세창고(03011{idx:03d})"

        total_usd = round(total_krw / 1350.0)
        payment_amount = round(total_krw / rate)
        rep = _REPRESENTATIVES[idx % len(_REPRESENTATIVES)]
        cc = _customs_code(meta["company_id"], idx)

        headers.append({
            # 대표값/식별 (기존 호환)
            "id": decl_id,
            "company_id": meta["company_id"],
            "declaration_no": ext.get("declaration_no"),
            "hs_code": _clean_hs(ext.get("hs_code")),
            "item_name": ext.get("item_name"),
            "declared_value": declared_value,
            "origin_country": origin_code,
            "origin_country_name": origin_nm,
            "import_date": ext.get("import_date"),
            "status": meta["status"],
            # 영역1
            "customs_office_code": customs_office,
            "declaration_type": "B 일반수입(내수용)",
            "clearance_plan": "C 장치후신고",
            "filer_name": meta["customs_broker_firm"],
            "filer_representative": f"관세사 {rep}",
            "importer_name": meta["company_name"],
            "importer_person_name": rep,
            "importer_customs_code": cc,
            "importer_is_taxpayer": "A",
            "taxpayer_address": f"({meta['address_postal_code']}) {meta['address']} {meta['address_detail']}",
            "taxpayer_name": meta["company_name"],
            "taxpayer_person_name": rep,
            "taxpayer_phone": _phone(idx),
            "taxpayer_email": _email(idx, meta["company_id"]),
            "taxpayer_customs_code": cc,
            "taxpayer_business_no": _tax_no(idx),
            "overseas_supplier_name": meta["related_companies"],
            "overseas_supplier_country": origin_nm,
            "overseas_supplier_code": f"OVS{idx:04d}",
            # 영역2
            "electronic_invoice_no": f"EI-2026-{decl_id:06d}",
            "bl_awb_no": bl_awb,
            "cargo_control_no": f"26KRC{decl_id:07d}",
            "master_bl_awb_no": master_bl,
            "forwarder_name": forwarder[0],
            "forwarder_code": forwarder[1],
            "departure_country": origin_nm,
            "arrival_port": arrival_port,
            "transport_type": transport_type,
            "vessel_name": vessel_name,
            "vessel_nationality": vessel_nat,
            "carrier_code": f"CAR{idx:03d}",
            "arrival_date": _shift_date(ext.get("import_date"), -3),
            "warehousing_date": _shift_date(ext.get("import_date"), -1),
            "inspection_location": inspection,
            "total_weight": round(sum_net * 1.08, 1),
            "total_weight_unit": "KG",
            "total_packages": sum_pkg,
            "package_type": detail["package_type"],
            # 영역3
            "transaction_type": "11 일반형태수입",
            "import_type": "21 내수용",
            "collection_type": "11 사후납부",
            "origin_cert_flag": detail["origin_cert"],
            "price_declaration_flag": "Y",
            "payment_incoterms": detail["incoterms"],
            "payment_currency": currency,
            "payment_amount": payment_amount,
            "payment_method": "11 T/T 사후송금",
            "exchange_rate": rate,
            "freight_krw": round(total_krw * 0.035),
            "insurance_krw": round(total_krw * 0.0025),
            "addition_krw": 0,
            "deduction_krw": 0,
            "total_customs_value_usd": total_usd,
            "total_customs_value_krw": total_krw,
            # 영역5
            "tax_customs_duty": sum_duty,
            "tax_individual_consumption": 0,
            "tax_traffic": 0,
            "tax_liquor": 0,
            "tax_education": 0,
            "tax_rural_special": 0,
            "tax_vat": sum_vat,
            "penalty_late_declaration": 0,
            "penalty_non_declaration": 0,
            "total_tax_amount": sum_duty + sum_vat,
            "total_vat_base": total_krw + sum_duty,
            "total_vat_exempt_base": 0,
        })

    return headers, items, specs, taxes


def build_company_rows(company_meta: list[dict], extracts: list[dict]) -> list[tuple]:
    """company_profiles 행(20-튜플) 생성."""
    rows = []
    for idx, (meta, ext) in enumerate(zip(company_meta, extracts), 1):
        declared_value = int(ext.get("declared_value_krw") or 0)
        annual_import = round(declared_value * meta["annual_multiplier"])
        annual_revenue = round(annual_import * 1.65)
        duty = round(annual_import * meta["duty_rate"])
        refund = round(annual_import * meta["refund_rate"])
        rows.append((
            meta["company_id"], meta["company_name"], _tax_no(idx), meta["industry_code"],
            meta["founded_year"], meta["risk_level"], meta["risk_score"], "2026-04-15",
            meta["address_postal_code"], meta["address"], meta["address_detail"],
            meta["employee_count"], meta["major_export_countries"], meta["customs_broker_firm"],
            meta["related_companies"], annual_revenue, annual_import, duty, refund,
            meta["fta_reduction_rate"],
        ))
    return rows


def build_risk_rows(company_meta: list[dict], risk_id_start: int = 2001) -> list[tuple]:
    """import_risk_scores 행(11-튜플) 생성."""
    rows = []
    for idx, meta in enumerate(company_meta, 1):
        rows.append((
            risk_id_start + idx - 1, meta["company_id"], meta["risk_level"], meta["risk_score"],
            *meta["risk"], "2026-08-05 09:00:00",
        ))
    return rows


def insert_dicts(con, table: str, cols: list[str], rows: list[dict]) -> None:
    """컬럼 명시 INSERT (positional 의존 제거)."""
    if not rows:
        return
    placeholders = ",".join(["?"] * len(cols))
    collist = ",".join(cols)
    con.executemany(
        f"INSERT INTO {table} ({collist}) VALUES ({placeholders})",
        [tuple(r.get(c) for c in cols) for r in rows],
    )


def main() -> None:
    extracts = json.loads(EXTRACT_PATH.read_text(encoding="utf-8"))
    if len(extracts) != len(COMPANY_META):
        raise RuntimeError(f"expected {len(COMPANY_META)} extracts, got {len(extracts)}")

    backup = DB_PATH.with_name(f"{DB_PATH.stem}.backup-{datetime.now():%Y%m%d-%H%M%S}{DB_PATH.suffix}")
    shutil.copy2(DB_PATH, backup)
    print(f"backup: {backup}")

    con = duckdb.connect(str(DB_PATH))
    company_ids = [row["company_id"] for row in COMPANY_META]
    placeholders = ",".join(["?"] * len(company_ids))

    # 자식 → 부모 순으로 기존 행 삭제 (이 회사들 신고분)
    con.execute(
        f"""
        DELETE FROM import_declaration_item_taxes WHERE item_id IN (
            SELECT i.item_id FROM import_declaration_items i
            JOIN import_declarations d ON i.declaration_id = d.id
            WHERE d.company_id IN ({placeholders}))
        """,
        company_ids,
    )
    con.execute(
        f"""
        DELETE FROM import_declaration_item_specs WHERE item_id IN (
            SELECT i.item_id FROM import_declaration_items i
            JOIN import_declarations d ON i.declaration_id = d.id
            WHERE d.company_id IN ({placeholders}))
        """,
        company_ids,
    )
    con.execute(
        f"""
        DELETE FROM import_declaration_items WHERE declaration_id IN (
            SELECT id FROM import_declarations WHERE company_id IN ({placeholders}))
        """,
        company_ids,
    )
    con.execute(f"DELETE FROM import_risk_scores WHERE company_id IN ({placeholders})", company_ids)
    con.execute(f"DELETE FROM import_declarations WHERE company_id IN ({placeholders})", company_ids)
    con.execute(f"DELETE FROM company_profiles WHERE company_id IN ({placeholders})", company_ids)

    company_rows = build_company_rows(COMPANY_META, extracts)
    headers, items, specs, taxes = build_declaration_rows(COMPANY_META, extracts)
    risk_rows = build_risk_rows(COMPANY_META)

    con.executemany(
        "INSERT INTO company_profiles VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        company_rows,
    )
    insert_dicts(con, "import_declarations", HEADER_COLS, headers)
    insert_dicts(con, "import_declaration_items", ITEM_COLS, items)
    insert_dicts(con, "import_declaration_item_specs", SPEC_COLS, specs)
    insert_dicts(con, "import_declaration_item_taxes", TAX_COLS, taxes)
    con.executemany(
        "INSERT INTO import_risk_scores VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        risk_rows,
    )

    # 비교군(SYN-*) 기업명/주소 정비 — 기존 동작 유지
    synthetic_rows = []
    existing = con.execute(
        "SELECT company_id, industry_code FROM company_profiles WHERE company_id LIKE 'SYN-%' ORDER BY company_id"
    ).fetchall()
    counters: dict[str, int] = {}
    for company_id, industry_code in existing:
        names = SYNTHETIC_NAMES.get(industry_code, ["에스앤티무역", "케이글로벌", "해온상사", "다온트레이드"])
        pos = counters.get(industry_code, 0)
        counters[industry_code] = pos + 1
        base = names[pos % len(names)]
        suffix = (pos // len(names)) + 1
        name = base if suffix == 1 else f"{base}{suffix}"
        synthetic_rows.append((name, "00000", f"{industry_code} 비교군 샘플 주소", "비교군 데이터", f"{name} 관세대행", company_id))
    con.executemany(
        """
        UPDATE company_profiles
        SET company_name = ?, address_postal_code = ?, address = ?,
            address_detail = ?, customs_broker_firm = ?
        WHERE company_id = ?
        """,
        synthetic_rows,
    )

    print(f"inserted companies: {len(company_rows)}")
    print(f"inserted declarations(header): {len(headers)}")
    print(f"inserted items: {len(items)} / specs: {len(specs)} / taxes: {len(taxes)}")
    print(f"inserted risk rows: {len(risk_rows)}")
    print(f"renamed synthetic peers: {len(synthetic_rows)}")


if __name__ == "__main__":
    main()
