"""Refresh DuckDB sample company/declaration/risk data with realistic demo rows.

The 13 primary rows are based on the PDF extraction cache generated by
extract_import_pdf_samples.py. They are still demo data, but the company names,
addresses, customs brokers, declarations, and risk indicators are shaped to
look like coherent importer profiles instead of placeholder "(샘플)업종기업" rows.
"""

from __future__ import annotations

import json
import shutil
from datetime import datetime
from pathlib import Path

import duckdb


ROOT = Path(__file__).resolve().parents[2]
DB_PATH = ROOT / "data" / "customs.duckdb"
EXTRACT_PATH = ROOT / "data" / "sample_import_pdf_extracts.json"


COMPANY_META = [
    {
        "company_id": "C-2001",
        "company_name": "홈리빙코리아 주식회사",
        "industry_code": "G46",
        "founded_year": 2012,
        "address_postal_code": "04526",
        "address": "서울특별시 중구 세종대로 136",
        "address_detail": "파이낸스센터 18층",
        "employee_count": 84,
        "major_export_countries": "인도네시아, 베트남, 중국",
        "customs_broker_firm": "세종합동관세사무소",
        "related_companies": "Home Living Asia Pte. Ltd.",
        "annual_multiplier": 9.5,
        "duty_rate": 0.076,
        "refund_rate": 0.012,
        "fta_reduction_rate": 10.0,
        "risk_level": "MEDIUM",
        "risk_score": 61.8,
        "risk": (48.0, 18.0, 24.0, 12.0, 35.0, 16.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2002",
        "company_name": "코리아디지털트레이딩 주식회사",
        "industry_code": "G46",
        "founded_year": 2018,
        "address_postal_code": "06158",
        "address": "서울특별시 강남구 테헤란로 419",
        "address_detail": "강남파이낸스플라자 9층",
        "employee_count": 42,
        "major_export_countries": "중국, 홍콩, 대만",
        "customs_broker_firm": "한빛관세법인",
        "related_companies": "Korea Trading HK Ltd.",
        "annual_multiplier": 14.0,
        "duty_rate": 0.061,
        "refund_rate": 0.018,
        "fta_reduction_rate": 6.5,
        "risk_level": "HIGH",
        "risk_score": 76.4,
        "risk": (72.0, 38.0, 19.0, 22.0, 54.0, 36.0),
        "status": "INSPECT",
    },
    {
        "company_id": "C-2003",
        "company_name": "세미콘솔루션코리아 유한회사",
        "industry_code": "C28",
        "founded_year": 2009,
        "address_postal_code": "18469",
        "address": "경기도 화성시 동탄첨단산업1로 27",
        "address_detail": "동탄테크노밸리 A동 1104호",
        "employee_count": 118,
        "major_export_countries": "일본, 미국, 싱가포르",
        "customs_broker_firm": "동탄관세법인",
        "related_companies": "Semicon Solution Japan KK",
        "annual_multiplier": 8.0,
        "duty_rate": 0.044,
        "refund_rate": 0.006,
        "fta_reduction_rate": 4.2,
        "risk_level": "MEDIUM",
        "risk_score": 69.7,
        "risk": (42.0, 34.0, 11.0, 8.0, 63.0, 28.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2004",
        "company_name": "프레시푸드코리아 주식회사",
        "industry_code": "G46",
        "founded_year": 2015,
        "address_postal_code": "22379",
        "address": "인천광역시 중구 축항대로 64",
        "address_detail": "냉동물류센터 3층",
        "employee_count": 73,
        "major_export_countries": "태국, 페루, 칠레",
        "customs_broker_firm": "인천항관세사법인",
        "related_companies": "Fresh Food Thailand Co., Ltd.",
        "annual_multiplier": 6.5,
        "duty_rate": 0.094,
        "refund_rate": 0.031,
        "fta_reduction_rate": 38.5,
        "risk_level": "HIGH",
        "risk_score": 82.1,
        "risk": (58.0, 42.0, 71.0, 64.0, 33.0, 27.0),
        "status": "HOLD",
    },
    {
        "company_id": "C-2005",
        "company_name": "펫라이프코리아 주식회사",
        "industry_code": "G47",
        "founded_year": 2020,
        "address_postal_code": "10403",
        "address": "경기도 고양시 일산동구 중앙로 1036",
        "address_detail": "웨스턴타워 1208호",
        "employee_count": 31,
        "major_export_countries": "튀르키예, 중국, 캐나다",
        "customs_broker_firm": "고양관세사무소",
        "related_companies": "Pet Life Global Trading",
        "annual_multiplier": 18.0,
        "duty_rate": 0.052,
        "refund_rate": 0.011,
        "fta_reduction_rate": 13.0,
        "risk_level": "MEDIUM",
        "risk_score": 55.9,
        "risk": (31.0, 22.0, 20.0, 16.0, 29.0, 18.0),
        "status": "NORMAL",
    },
    {
        "company_id": "C-2006",
        "company_name": "메디케어코리아 유한회사",
        "industry_code": "C27",
        "founded_year": 2016,
        "address_postal_code": "08390",
        "address": "서울특별시 구로구 디지털로 288",
        "address_detail": "대륭포스트타워 2차 705호",
        "employee_count": 56,
        "major_export_countries": "대만, 일본, 독일",
        "customs_broker_firm": "구로디지털관세법인",
        "related_companies": "Medicare Taiwan Ltd.",
        "annual_multiplier": 22.0,
        "duty_rate": 0.048,
        "refund_rate": 0.007,
        "fta_reduction_rate": 9.0,
        "risk_level": "MEDIUM",
        "risk_score": 64.2,
        "risk": (28.0, 21.0, 16.0, 9.0, 58.0, 19.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2007",
        "company_name": "스타일플러스코리아 주식회사",
        "industry_code": "C13",
        "founded_year": 2011,
        "address_postal_code": "04782",
        "address": "서울특별시 성동구 아차산로 17",
        "address_detail": "서울숲IT밸리 1002호",
        "employee_count": 97,
        "major_export_countries": "베트남, 방글라데시, 캄보디아",
        "customs_broker_firm": "성동관세법인",
        "related_companies": "Style Plus Vietnam Co., Ltd.",
        "annual_multiplier": 7.2,
        "duty_rate": 0.13,
        "refund_rate": 0.025,
        "fta_reduction_rate": 47.0,
        "risk_level": "HIGH",
        "risk_score": 74.6,
        "risk": (63.0, 29.0, 68.0, 34.0, 51.0, 22.0),
        "status": "INSPECT",
    },
    {
        "company_id": "C-2008",
        "company_name": "헬스세이프코리아 주식회사",
        "industry_code": "C21",
        "founded_year": 2019,
        "address_postal_code": "34141",
        "address": "대전광역시 유성구 대학로 291",
        "address_detail": "바이오벤처센터 406호",
        "employee_count": 45,
        "major_export_countries": "말레이시아, 중국, 싱가포르",
        "customs_broker_firm": "충청관세법인",
        "related_companies": "Health Safe Malaysia Sdn. Bhd.",
        "annual_multiplier": 8.0,
        "duty_rate": 0.08,
        "refund_rate": 0.018,
        "fta_reduction_rate": 21.0,
        "risk_level": "MEDIUM",
        "risk_score": 67.5,
        "risk": (41.0, 24.0, 33.0, 22.0, 49.0, 21.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2009",
        "company_name": "오토파트코리아 주식회사",
        "industry_code": "C30",
        "founded_year": 2008,
        "address_postal_code": "16648",
        "address": "경기도 수원시 권선구 산업로 156",
        "address_detail": "수원산업단지 2동",
        "employee_count": 132,
        "major_export_countries": "독일, 멕시코, 중국",
        "customs_broker_firm": "경기관세법인",
        "related_companies": "Auto Parts Europe GmbH",
        "annual_multiplier": 6.8,
        "duty_rate": 0.055,
        "refund_rate": 0.013,
        "fta_reduction_rate": 18.0,
        "risk_level": "HIGH",
        "risk_score": 72.8,
        "risk": (46.0, 44.0, 18.0, 15.0, 66.0, 31.0),
        "status": "INSPECT",
    },
    {
        "company_id": "C-2010",
        "company_name": "키즈월드코리아 주식회사",
        "industry_code": "G47",
        "founded_year": 2017,
        "address_postal_code": "08510",
        "address": "서울특별시 금천구 벚꽃로 278",
        "address_detail": "SJ테크노빌 1510호",
        "employee_count": 66,
        "major_export_countries": "중국, 홍콩, 베트남",
        "customs_broker_firm": "금천합동관세사무소",
        "related_companies": "Kids World Shenzhen Trading",
        "annual_multiplier": 8.8,
        "duty_rate": 0.08,
        "refund_rate": 0.019,
        "fta_reduction_rate": 12.0,
        "risk_level": "HIGH",
        "risk_score": 73.5,
        "risk": (57.0, 35.0, 24.0, 18.0, 61.0, 26.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2011",
        "company_name": "브라이트테크코리아 주식회사",
        "industry_code": "C26",
        "founded_year": 2021,
        "address_postal_code": "14055",
        "address": "경기도 안양시 동안구 시민대로 327",
        "address_detail": "스마트스퀘어 614호",
        "employee_count": 28,
        "major_export_countries": "중국, 대만",
        "customs_broker_firm": "안양관세사무소",
        "related_companies": "Bright Tech Shenzhen Co., Ltd.",
        "annual_multiplier": 24.0,
        "duty_rate": 0.04,
        "refund_rate": 0.009,
        "fta_reduction_rate": 5.0,
        "risk_level": "MEDIUM",
        "risk_score": 66.9,
        "risk": (54.0, 39.0, 15.0, 11.0, 47.0, 33.0),
        "status": "REVIEW",
    },
    {
        "company_id": "C-2012",
        "company_name": "키친메이트코리아 주식회사",
        "industry_code": "G46",
        "founded_year": 2014,
        "address_postal_code": "07238",
        "address": "서울특별시 영등포구 은행로 11",
        "address_detail": "일신빌딩 703호",
        "employee_count": 52,
        "major_export_countries": "중국, 베트남, 인도네시아",
        "customs_broker_firm": "여의도관세법인",
        "related_companies": "Kitchen Mate Ningbo Co., Ltd.",
        "annual_multiplier": 17.0,
        "duty_rate": 0.082,
        "refund_rate": 0.015,
        "fta_reduction_rate": 17.5,
        "risk_level": "MEDIUM",
        "risk_score": 59.8,
        "risk": (38.0, 27.0, 25.0, 17.0, 37.0, 20.0),
        "status": "NORMAL",
    },
    {
        "company_id": "C-2013",
        "company_name": "뷰티코리아 주식회사",
        "industry_code": "G46",
        "founded_year": 2010,
        "address_postal_code": "06019",
        "address": "서울특별시 강남구 도산대로 317",
        "address_detail": "호림아트센터 8층",
        "employee_count": 91,
        "major_export_countries": "프랑스, 이탈리아, 미국",
        "customs_broker_firm": "강남관세법인",
        "related_companies": "Beauty Korea Paris SARL",
        "annual_multiplier": 7.0,
        "duty_rate": 0.064,
        "refund_rate": 0.014,
        "fta_reduction_rate": 29.0,
        "risk_level": "HIGH",
        "risk_score": 75.2,
        "risk": (62.0, 41.0, 47.0, 21.0, 45.0, 35.0),
        "status": "INSPECT",
    },
]


ORIGIN_FIX = {
    "THAILAND": "THA",
    "CN": "CHN",
    "JP": "JPN",
    "TW": "TWN",
    "TR": "TUR",
    "VN": "VNM",
    "MY": "MYS",
    "DE": "DEU",
    "FR": "FRA",
}


SYNTHETIC_NAMES = {
    "C20": ["동진케미칼", "한서소재", "대양폴리머", "케이피화학무역"],
    "G46": ["서진글로벌트레이드", "태원인터내셔널", "유니온소싱", "에이스커머스"],
    "C13": ["한빛어패럴", "신성텍스타일", "동남섬유", "오름패브릭"],
    "C26": ["넥스전자부품", "루멘테크", "에스엠디솔루션", "코어일렉트로닉스"],
    "C30": ["진성모빌리티", "태광오토텍", "케이모터스부품", "우진브레이크"],
    "C21": ["바이오세이프", "메디젠랩", "휴먼헬스케어", "케이파마소싱"],
    "G47": ["리빙앤리테일", "제이펫커머스", "키즈앤홈", "제주라이프몰"],
}


def _clean_hs(value: str | None) -> str:
    return (value or "").replace(".", "").replace("-", "")[:10]


def _origin(value: str | None) -> str:
    text = (value or "").strip().upper()
    for key, code in ORIGIN_FIX.items():
        if key in text:
            return code
    return text[:3] if text else "UNK"


def _tax_no(index: int) -> str:
    return f"{100 + index:03d}-88-{42000 + index * 137:05d}"


def main() -> None:
    extracts = json.loads(EXTRACT_PATH.read_text(encoding="utf-8"))
    if len(extracts) != len(COMPANY_META):
        raise RuntimeError(f"expected {len(COMPANY_META)} extracts, got {len(extracts)}")

    backup = DB_PATH.with_name(f"{DB_PATH.stem}.backup-{datetime.now():%Y%m%d-%H%M%S}{DB_PATH.suffix}")
    shutil.copy2(DB_PATH, backup)
    print(f"backup: {backup}")

    con = duckdb.connect(str(DB_PATH))
    company_ids = [row["company_id"] for row in COMPANY_META]
    placeholders = ",".join(["?"] * len(company_ids))
    con.execute(f"DELETE FROM import_risk_scores WHERE company_id IN ({placeholders})", company_ids)
    con.execute(f"DELETE FROM import_declarations WHERE company_id IN ({placeholders})", company_ids)
    con.execute(f"DELETE FROM company_profiles WHERE company_id IN ({placeholders})", company_ids)

    company_rows = []
    declaration_rows = []
    risk_rows = []
    decl_start = 2001
    risk_start = 2001

    for idx, (meta, ext) in enumerate(zip(COMPANY_META, extracts), 1):
        declared_value = int(ext["declared_value_krw"] or 0)
        annual_import = round(declared_value * meta["annual_multiplier"])
        annual_revenue = round(annual_import * 1.65)
        duty = round(annual_import * meta["duty_rate"])
        refund = round(annual_import * meta["refund_rate"])
        company_rows.append((
            meta["company_id"],
            meta["company_name"],
            _tax_no(idx),
            meta["industry_code"],
            meta["founded_year"],
            meta["risk_level"],
            meta["risk_score"],
            "2026-04-15",
            meta["address_postal_code"],
            meta["address"],
            meta["address_detail"],
            meta["employee_count"],
            meta["major_export_countries"],
            meta["customs_broker_firm"],
            meta["related_companies"],
            annual_revenue,
            annual_import,
            duty,
            refund,
            meta["fta_reduction_rate"],
        ))

        declaration_rows.append((
            decl_start + idx - 1,
            meta["company_id"],
            ext["declaration_no"],
            _clean_hs(ext.get("hs_code")),
            ext["item_name"],
            declared_value,
            _origin(ext.get("origin_country")),
            ext["import_date"],
            meta["status"],
        ))

        risk_rows.append((
            risk_start + idx - 1,
            meta["company_id"],
            meta["risk_level"],
            meta["risk_score"],
            *meta["risk"],
            "2026-08-05 09:00:00",
        ))

    con.executemany(
        """
        INSERT INTO company_profiles VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        company_rows,
    )
    con.executemany(
        """
        INSERT INTO import_declarations VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        declaration_rows,
    )
    con.executemany(
        """
        INSERT INTO import_risk_scores VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        risk_rows,
    )

    synthetic_rows = []
    existing = con.execute(
        "SELECT company_id, industry_code FROM company_profiles WHERE company_id LIKE 'SYN-%' ORDER BY company_id"
    ).fetchall()
    counters: dict[str, int] = {}
    for company_id, industry_code in existing:
        names = SYNTHETIC_NAMES.get(industry_code, ["에스앤티무역", "케이글로벌", "해온상사", "다온트레이드"])
        pos = counters.get(industry_code, 0)
        counters[industry_code] = pos + 1
        base = names[pos % len(names)]
        suffix = (pos // len(names)) + 1
        name = base if suffix == 1 else f"{base}{suffix}"
        synthetic_rows.append((name, "00000", f"{industry_code} 비교군 샘플 주소", "비교군 데이터", f"{name} 관세대행", company_id))
    con.executemany(
        """
        UPDATE company_profiles
        SET company_name = ?,
            address_postal_code = ?,
            address = ?,
            address_detail = ?,
            customs_broker_firm = ?
        WHERE company_id = ?
        """,
        synthetic_rows,
    )

    print(f"inserted companies: {len(company_rows)}")
    print(f"inserted declarations: {len(declaration_rows)}")
    print(f"inserted risk rows: {len(risk_rows)}")
    print(f"renamed synthetic peers: {len(synthetic_rows)}")


if __name__ == "__main__":
    main()
